{{- range $scheduleName, $schedule := .Values.schedules }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "velero.fullname" $ }}-{{ $scheduleName }}
  annotations:
  {{- if $schedule.annotations }}
    {{- toYaml $schedule.annotations | nindent 4 }}
  {{- end }}
  {{- if $.Values.customAnnotations }}
  {{- toYaml $.Values.customAnnotations | nindent 4 }}
  {{- end }}
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    helm.sh/chart: {{ include "velero.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: {{ template "velero.name" $ }}
    app.kubernetes.io/name: {{ include "velero.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    {{- if $.Values.customLabels }}
    {{ toYaml $.Values.customLabels }}
    {{- end }}
    {{- if $schedule.labels }}
      {{- toYaml $schedule.labels | nindent 4 }}
    {{- end }}
spec:
{{- if $schedule.useOwnerReferencesInBackup }}
  useOwnerReferencesInBackup: {{ $schedule.useOwnerReferencesInBackup }}
{{- end }}
  schedule: {{ $schedule.schedule | quote }}
{{- with $schedule.template }}
  template:
    {{- toYaml . | nindent 4 }}
{{- end }}
---
{{- end }}
